stages:
  train_model:
    cmd: python src/train.py
    deps:
    - data/iris.csv
    - src/train.py
    outs:
    - src/model.pkl
    metrics:
    - metrics.json
    params:
    - train.n_estimators
    - train.random_state
    - train.test_size
